### ISSUE TITLE
vowifi calling issue

### ISSUE THREAD

**Issue by TheAzurite** [ManshuTyagi/device_realme_RMX2001#1]
hello sir
I am rahul form rmx2001 user, I love to use custom rom and custom kernel, The problem is that rmx2001 WIFI calling not working any custom rom, I hope you will be fix this problem next update ….thank you

**Comment by ManshuTyagi** [comment]
![Screenshot_20210207-144620~2](https://user-images.githubusercontent.com/74397342/107143032-bd5d9f00-6958-11eb-9893-e316f139908f.png)

![Screenshot_20210207-151457_Phone~2](https://user-images.githubusercontent.com/74397342/107143037-c2225300-6958-11eb-9d15-668cb3fac36c.png)

@TheAzurite u can see it's working fine

**Comment by ManshuTyagi** [comment]
@ManshuTyagi ye dekh
